spring:
  profiles.active: default
  
---

spring:
  profiles: default
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://localhost:3306/dusky-alumni?useSSL=false
    username: root
    password: root
    dbcp:
      validation-query: SELECT 1 
      test-on-borrow: true 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
  application:
    name: alumni-service
logging:
  level:
    org.springframework: false
    org.hibernate: ERROR
  path: logs/dev/
server:
  context-path: /api
  port: 8090

---

spring:
  profiles: docker
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://alumni-sql:3306/dusky-alumni?useSSL=false
    username: root
    password: susl
    dbcp:
      validation-query: SELECT 1 
      test-on-borrow: true 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
  application:
    name: alumni-service
logging:
  level:
    org.springframework: false
    org.hibernate: ERROR
  path: logs/dev/
server:
  context-path: /api
  port: 8090
  
  